Update DevOps pipeline configuration in main2.yml

diff --git a/.github/workflows/main2.yml b/.github/workflows/main2.yml
--- a/.github/workflows/main2.yml
+++ b/.github/workflows/main2.yml
@@ -1,9 +1,19 @@
-name: Devops-pipeline
+name: Devops-pipeline Project Masoud
 
 on:
   push:
-    branches: [ "De25-ms" ]
+    branches: [ "main" ]
   workflow_dispatch:
+    inputs:
+      log_error:
+        description: "upload error log if tests fail"
+        required: true
+        default: "true"
+        type: choice
+        options:
+          - "true"
+          - "false"
+  
 
 jobs:
 
@@ -15,24 +25,32 @@ jobs:
 
       - name: Create .env file
         run: |
-          echo "COINMARKET_API_KEY=${{ secrets.COINMARKET_API_KEY }}" >> .env
+          echo "COINMARKETCAP_API_KEY=${{ secrets.COINMARKETCAP_API_KEY }}" >> .env
           echo "COINMARKETCAP_SYMBOLS=${{ secrets.COINMARKETCAP_SYMBOLS }}" >> .env
           echo "UPDATE_FREQ_SEC=${{ secrets.UPDATE_FREQ_SEC }}" >> .env
 
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+
+
       - name: Unit and integration test
         run: |
-          pytest tests/test_crypto_api.py || (echo "Tester misslyckades, se detaljer nedan:" > error.log && pytest tests/test_crypto_api.py >> error.log 2>&1)
+          PYTHONPATH=src pytest src/tests/test_crypto_api.py || (
+            echo "tests failed, see below:" > error.log
+            PYTHONPATH=src pytest src/tests/test_crypto_api.py >> error.log 2>&1
+            exit 1
+          )
 
-  log_errors:
-    needs: test
-    runs-on: ubuntu-latest
-    if: ${{ needs.test.result == 'failure' && github.event.inputs.log_errors == 'true' }}
-    steps:
       - name: Upload error log
+        if: ${{ failure() && (github.event.inputs.log_errors == 'true' || github.event_name != 'workflow_dispatch') }}
         uses: actions/upload-artifact@v4
         with:
           name: error-log
           path: error.log
+
+
 
   build-and-push:
     needs: test
